# Generated by Django 2.1.3 on 2018-12-24 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('nickname', models.CharField(max_length=20)),
                ('update_date', models.DateTimeField(verbose_name='date updated')),
            ],
        ),
    ]
