# Generated by Django 2.1.3 on 2018-12-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20181224_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsdata',
            name='comments',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='commentsdata',
            name='nickname',
            field=models.CharField(default='', max_length=20),
        ),
    ]
